version: "3.9"

services:
  api:
    container_name: agent-demo-api
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    container_name: agent-demo-frontend
    build:
      context: ..
      dockerfile: web/Dockerfile
      args:
        VITE_API_BASE_URL: ""
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped
